apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
    - port: 5050
      targetPort: 3000
      nodePort: 33333
  selector:
    component: webapisimpleblog